log:
  level: info
  file: ""

plugin:

  - tag: main_server
    type: server
    args:
      entry:
        - _default_cache
        - main_sequence
      max_concurrent_queries: 0
      server:
        - protocol: udp
          addr: 127.0.0.1:5353
        - protocol: tcp
          addr: 127.0.0.1:5353

  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if:
            - query_is_ad_domain
          exec:
            - _block_with_nxdomain
            - _end

        - if:
            - query_is_local_domain
            - "!_query_is_common"
          exec:
            - forward_local
            - _end

        - if:
            - query_is_non_local_domain
          exec:
            - forward_remote
            - _end

        - forward_local
        - if:
            - response_has_local_ip
          goto: _end
        - forward_remote


  - tag: forward_local
    type: forward
    args:
      upstream:
        - addr: https://223.5.5.5/dns-query
        - addr: https://dns.pub/dns-query

  - tag: forward_remote
    type: forward
    args:
      upstream:
        - addr: https://1.1.1.1/dns-query
        - addr: https://8.8.8.8/dns-query

  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - ./geosite.dat:cn

  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - ./geosite.dat:geolocation-!cn

  - tag: query_is_ad_domain
    type: query_matcher
    args:
      domain:
        - ./geosite.dat:category-ads-all

  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - ./geoip.dat:cn
